replicaCount: 1

name: parser
image:
  repository: "eu.gcr.io/test-21111992/parser"
  tag: "1.1.0"
  pullPolicy: Always
  pullSecret: "helm-secret"
nameOverride: ""
fullnameOverride: ""

containerPort: 9001

service:
  type: ClusterIP
  port: 9001

mariadb:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "metrics"
  rootUser:
    password: "qwerty56"
  db:
    user: "demchenko"
    name: "test_database"
  metrics:
    enabled: true



