replicaCount: 1

name: parser
image:
  repository: "eu.gcr.io/test-21111992/parser"
  tag: "1.1.0"
  pullPolicy: Always
  pullSecret: "helm-secret"
nameOverride: ""
fullnameOverride: ""

containerPort: 9001

service:
  type: ClusterIP
  port: 9001